<a href="https://colab.research.google.com/github/pujaroy280/Data-Analytics-Microcredential/blob/main/(Puja_Roy)_Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Problems

____________

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 20 zeros 

In [2]:
arr1 = np.zeros(20)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Create an array of 10 ones

In [3]:
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
# Easy way to fill array: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-13.php
arr3 = np.ones(10) * 5
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
arr4 = np.arange(10,51)
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
arr5 = np.arange(10,51,2)
arr5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
my_list = [[0,1,2],[3,4,5],[6,7,8]]
np.array(my_list)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.rand()

0.5390373183208921

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
np.random.rand(5,5)

array([[0.03084535, 0.88434547, 0.45634299, 0.65289715, 0.04847097],
       [0.54558776, 0.46082494, 0.80565801, 0.5567043 , 0.6205403 ],
       [0.66913487, 0.42555093, 0.37584554, 0.4024318 , 0.64801661],
       [0.49995172, 0.25922863, 0.35320052, 0.37199806, 0.86312889],
       [0.82656497, 0.62595466, 0.94204168, 0.93679378, 0.41746544]])

#### Create the following matrix:

In [11]:
arr6 = np.arange(1,101)
arr6.reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
import numpy as np
#mat = np.arange(1,27).reshape(5,5)
mat = np.arange(1,28).reshape(9,3)
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [14]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [15]:
"""
Another method

new_mat = mat[(27>mat) & (mat>11)].reshape(3,5)
new_mat[:,0:4]
"""

np.array(mat[(27>mat) & (mat>11)]).reshape(3,5)[:,0:4]
# Used as reference: https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [16]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [17]:
mat[6][1]

20

In [18]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [19]:
np.array([mat[0,1],mat[2,0],mat[3,2]]).reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [20]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [21]:
np.array(mat[(mat >= 21) & (mat < 26)])

array([21, 22, 23, 24, 25])

In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [23]:
np.array(mat[(mat >= 16) & (mat <= 25)]).reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now,

#### Get the sum of all the values in mat

In [24]:
x = 0
y = 0
sum = 0

# Iterate through each row in the matrix; iterate 8 times.
while y < 9:
  # For each row, itertate through each column. In this case, iterates 3 times.
    while x < 3:
        sum += mat[y][x]    # Add to sum the number at mat[row][column]
        x+= 1
    y += 1
    # Increment y(row) and initialize x to zero since, at this point, x=3.
    x = 0

print(sum)


378


In [25]:
# Reference of finding Method to get sum of a matrix: https://numpy.org/doc/stable/reference/generated/numpy.sum.html
np.sum(mat)

378

#### Get the standard deviation of the values in mat

In [26]:
# Reference of standard deviation method: https://numpy.org/doc/stable/reference/generated/numpy.std.html
np.std(mat)

7.788880963698615

#### Get the sum of all the columns in mat

In [27]:
# Reference of Function to find the sum of columns of matrix in Python: https://www.delftstack.com/howto/numpy/sum-of-columns-matrix-numpy/

s= np.sum(mat,axis=0)
s


array([117, 126, 135])

In [28]:
# Confused about last part

# Cheers!